apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kanameos-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "200m"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - os.vahry.my.id
      secretName: kanameos-tls
  rules:
    - host: os.vahry.my.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kanameos
                port:
                  number: 80
